### ISSUE TITLE
Data Connector page in Tabeau stuck at Querying data...

### ISSUE THREAD

**Issue by that-dom** [mradamlacey/elasticsearch-tableau-connector#1]
I got a fresh node of CentOS loaded with nginx, grunt, and grunt-cli load. Used grunt-cli to install the web connector in the default location of /usr/nginx/html/public/elasticsearch-connector.html. When I browse to this url I get please open this URL from within Tableau but when I load it in Tableau I get the same message. I started it with nodejs on port 30000 but get the same message in both places.
I haven't been able to get it to pull up the configuration page.
What am I doing wrong here?

**Comment by mradamlacey** [comment]
Can you run browser debugging tools from the Simulator SDK and make sure you don't see any errors?  I suspect that for some reason the Tableau JS SDK is not being loaded correctly from their CDN.

If you copy the console output here that should help in debugging.

The message of 'Please open this URL from within Tableau' is triggered off of the Tableau lifecycle methods being invoked - which should happen from within the Simulator SDK or from within Tableau Desktop or Server.

**Comment by that-dom** [comment]
Thanks for the quick response. 
The output I got from the simulator was:
Uncaught ReferenceError: $ is not defined stack:ReferenceError: $ is not defined at Object.myConnector.init (http://{localserverip}/public/elasticsearch-connector.html:279:5) at _receiveMessage (https://public.tableau.com/javascripts/api/tableauwdc-1.1.0.js:143:21)

I was able to load tableauwdc-1.1.0.js from my workstation as well as the backend server that's hosting the web connector.

**Comment by mradamlacey** [comment]
So it looks like jQuery for some reason is not being loaded - that's the issue with the null reference for `$`

Can you capture a network trace, if you are using Chrome, from the Network tab, reload the page and then right click in the table and selected 'Copy All as HAR' and you can upload here I that might indicate what the browser is loading.

Otherwise you could grab a screenshot of the Network tab too.

And just to check, to install you ran:

```
grunt build
grunt web
```

The `grunt build` step is critical to making sure all the JS is placed in the right folder.

**Comment by that-dom** [comment]
You're on to something there.
I'm new to grunt so I'm not sure what went wrong. I reinstalled nodejs, grunt and grunt-cli but the same issue was that it wasn't moving any of the js library's or css into the same folder as elasticsearch-connector.html. I manually downloaded all those packages that came up as 404 and it's giving me a new message. The new message is that it can't reach ES or CORS is disabled. I'm on the VPN now so I think it's a networking issue since I enabled CORS this morning and restarted ES. I'll open a new message if I can't work through it tomorrow when I'm back in the office.
Thanks Adam, for your help and nice looking web connector.

**Comment by afranzi** [comment]
Hi, I'm trying to connect with our ElasticSearch from AWS and connector seems to be stuck in the execution query page.

I'm testing with WDC I'm getting:
`No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 403.`
