### ISSUE TITLE
Executing Query forever when set up connection

### ISSUE THREAD

**Issue by hugo-zheng** [mradamlacey/elasticsearch-tableau-connector#17]
Hi,

Thanks for your great work on the elasticsearch connector first!

I meet an issue at the end of Tableau Executing query part. in attachment, there is a video recorded the progress.

ENV: Macbook pro, elasticsearch 2.3.3 within Docker 1.11.2, tableau desktop 9.3
Data: only 1 piece:
`curl -XPUT 'http://localhost:9200/db/user/1' -d '
{
    "id": 1,
    "name": "hugo"
}'`
I run a elasticsearch service on my Mac, and use the connector to connect it.
It's fine on the connector webpage(see attachment "connector_fine_page" ), index, type showed itself.
But after click "submit" button, it turns to tableau loading popup,  the steps are: connecting to database, Executing query, Loading metadata, Creating extract database, Executing query... (then stops here, will run about 10 mins to pop a timeout page, see "Executing query forever", "finall error").

Much appreciate if you could look into this.

<img width="1065" alt="connector_fine_page" src="https://cloud.githubusercontent.com/assets/8509379/16582631/9ea770dc-42e2-11e6-80de-ef6649160269.png">

<img width="627" alt="executing query forever" src="https://cloud.githubusercontent.com/assets/8509379/16582853/45fbd25a-42e4-11e6-8105-6295ecd15f52.png">
<img width="551" alt="finall error" src="https://cloud.githubusercontent.com/assets/8509379/16582852/45fb4a1a-42e4-11e6-8996-eca114e27156.png">

[video.zip](https://github.com/mradamlacey/elasticsearch-tableau-connector/files/347577/video.zip)

**Comment by mradamlacey** [comment]
Can you provide the contents of the Tableau Desktop logs and see what is there?

**Comment by hugo-zheng** [comment]
Thanks for your quick reply, I checked with http://tableau.github.io/webdataconnector/Simulator/

**Comment by hugo-zheng** [comment]
seems, it keep calling getNextScrollResult
![screen shot 2016-07-06 at 3 50 16 pm](https://cloud.githubusercontent.com/assets/8509379/16611009/77b9aba2-4391-11e6-9180-75d096707bea.png)

**Comment by hugo-zheng** [comment]
just tried again, there only one record in es, if I set "Total limit on number of rows to sync" to 1, it works fine

**Comment by mradamlacey** [comment]
I suspect there's a bug when the total number of hits is less than the
limit specified in the connector.  I will push a fix for this asap.
