### ISSUE TITLE
Import to Tableau Server error

### ISSUE THREAD

**Issue by DinglingH** [mradamlacey/elasticsearch-tableau-connector#32]
I copied dist folder to Tableau Server, and ran following commands within dist folder
tabadmin import_webdataconnector elasticsearch-connector.html
tabadmin import_webdataconnector elasticsearch-connector.min.css
tabadmin import_webdataconnector elasticsearch-connector.min.js

And from Tableau go to 'Web Data Connector' and enter the URL of the connector:
http://.../webdataconnectors/elasticsearch-connector.html

It showed the connector html in Tableau Desktop, but had this error:
ReferenceError: Unable to process binding "aceEditor: function () {return undefined; }" Message: Can't find variable: ace file: http://.../webdataconnectors/elasticsearch-connector.min.js line: 24

**Comment by mradamlacey** [comment]
This should be fixed now.
