### ISSUE TITLE
connect without changing CORS config

### ISSUE THREAD

**Issue by NISHAgl** [mradamlacey/elasticsearch-tableau-connector#35]
I am using Elasticsearch service managed by AWS so we dont have access to elasticsearch.yml or anyway we cannot enable CORS support in Elasticsearch server.
Please suggest a way where we do not require the use of CORS and get the required data

**Comment by mradamlacey** [comment]
I think the only way to make this work without a server configuration change is to put something in front of Elasticsearch that send the CORS headers correctly to the Tableau client.

For AWS - here's a link that describes how to setup an API gateway that sends CORS headers: http://enable-cors.org/server_awsapigateway.html

You could standup an API gateway instance (with CORS enabled) that forwards requests to your Elasticsearch instance.

Then in the Elasticsearch URL in the Tableau connector - you would enter the URL of your API Gateway.  

Interested to know if that works for you.

**Comment by NISHAgl** [comment]
First of all a big thanks to you for replying in such a short time :) . And again thanks for sharing the link. I am going through this link and will definitely post back if it works fine
