### ISSUE TITLE
Elastic 5.0.0

### ISSUE THREAD

**Issue by pb4171** [mradamlacey/elasticsearch-tableau-connector#36]
Hi, I have tried to connect to the latest Elastic Version 5.0.0 and I can see on Tableau only the numeric fields; no string field is displayed. Tx in advance.

**Comment by chuchurocket27** [comment]
I can confirm this behavior - using Tableau 10.1, Elastic version 5.1 - cannot pull any non-numeric fields.

**Comment by mradamlacey** [comment]
Currently the connector uses the 1.1.1 version of the WDC SDK which is not compatible with Tableau 10+.

I am going to close this issue and open a new issue to add support for Tableau 10+.
