### ISSUE TITLE
Not Compatible with Elasticsearch 5.2.0

### ISSUE THREAD

**Issue by neuronring** [mradamlacey/elasticsearch-tableau-connector#49]
Hi, I am using ES 5.2.0., I downloaded the elasticsearch-tableau-connector release-1.0 from this link and built the package. When I launch WDC from my Tableau 9.3 Desktop instance, 

> http://my-elasticsearch-tableau-connector

Only the numeric fields are from my Elasticsearch index is visible. It is not showing any string fields.
Then i found this forum post, I was hoping that would fix the problem. But it didn't, when i change the JS file as shown here, the `grunt build:dist`  would just work fine, but when launch the WDC, it is throwing error on tableau.dataTypeEnum.string

Reference: https://community.tableau.com/message/581909

`31. RE: ELASTICSEARCH CONNECTOR
 Abed Arnaout
Vizitor
ABED ARNAOUT JAN 25, 2017 11:37 AM (IN RESPONSE TO ANDREA CAMPAGNA)
For those having issues with text fields in Elasticsearch 5.x, you can do the following fix (I'll also submit a merge request to github):
- In "elasticsearch-connector.js" file, make sure you have keyword & text fields in the elasticsearchTableauDataTypeMap as follow:
 

> var elasticsearchTableauDataTypeMap = {
>         string:  tableau.dataTypeEnum.string,
>   keyword:  tableau.dataTypeEnum.string,
>   text:  tableau.dataTypeEnum.string,
>         float:  tableau.dataTypeEnum.float,
>         long:  tableau.dataTypeEnum.int,
>         integer:  tableau.dataTypeEnum.int,
>         double:  tableau.dataTypeEnum.float,
>         date:  tableau.dataTypeEnum.datetime,
>         boolean:  tableau.dataTypeEnum.bool,
>         geo_point:  tableau.dataTypeEnum.string
>     },
>

**Comment by mradamlacey** [comment]
Currently the 1-0 release (with support for Tableau previous to 10.0 does NOT support Elasticsearch 5.2 currently...

Please submit a PR. Ideally this would be backwards compatible with Elasticsearch 2.x as well.

thanks!

**Comment by mradamlacey** [comment]
This has now been fixed.  From above, there was an additional change needed in `aggregations.js` to fix the support there.

FYI - the master and release-2.0 branch have support for Elasticsearch 5.*
