### ISSUE TITLE
An Error occured while communicating with the data source. 

### ISSUE THREAD

**Issue by pank9v** [mradamlacey/elasticsearch-tableau-connector#50]
I am seeing this issue when connecting to my elastic search server. This happens when I select (Search Result Mode). However, Aggregation mode works fine. 

![issue](https://cloud.githubusercontent.com/assets/4723281/24931995/5add0588-1ec4-11e7-8cdc-de96ac45d72e.PNG)

**Comment by mradamlacey** [comment]
Can you make sure you have the latest code (from the master branch) and see what the results are?  I believe this issue should be fixed.

When you load the connector UI make sure you hit the refresh button (in the top bar), it's possible the connector resources are cached.

**Comment by pank9v** [comment]
Hi Adam,

Thanks for your reply! I have tried the latest master code and yet I hit the same issue. This issue occurs when date fields are not type String. In such cases .replace() returns undefined and moment.utc(...) throws exception. As a result user is not able to retrieve any data while using (Search Result Mode).

It works the minute. I apply my proposed fix. 

https://github.com/mradamlacey/elasticsearch-tableau-connector/pull/51/files <https://github.com/mradamlacey/elasticsearch-tableau-connector/pull/51/files>


—
Thanks,
Pankaj

**Comment by mradamlacey** [comment]
This is now resolved.  Thanks for the fix @pank9v
