### ISSUE TITLE
"Invalid Elasticsearch URL" error, but the connector is pulling index and type data correctly

### ISSUE THREAD

**Issue by chuchurocket27** [mradamlacey/elasticsearch-tableau-connector#58]
My Elasticsearch URL is `http://lgb-es-01:9200`. When I populate the "Elasticsearch URL" with this, I can see and select my index and types correctly. But hitting "Preview" or "Submit" causes an "Elasticsearch URL is not a valid URL" error.

Running ES 5.4, Tableau 10.2.0.

**Comment by chuchurocket27** [comment]
The issue is in `app.js` it looks like:

    var isValidUrl = function (str) {
            var pattern = new RegExp

Looks like the regex does not expect numbers to be at the end of the URL. 

My suggestion is to not validate the URL at all, since an "Unable to get Elasticsearch indices" error will occur if the URL doesn't point to a valid ES server anyway.

**Comment by mradamlacey** [comment]
Yes, will update the regex, look for a fix for this soon.  thanks for identifying.
