### ISSUE TITLE
The connector does not load properly in Tableau designer

### ISSUE THREAD

**Issue by shihch** [mradamlacey/elasticsearch-tableau-connector#7]
Hi

I clone the repository run the build and start the connector by

```
node index,js
```

In the Tableau designer web data connector, 
if I put the URL http://localhost:3000 then I get error: "Cannot GET /"
if I put the URL http://localhost:3000/elasticsearch-connector.html, In the error detail shows:
TypeError: undefined is not an object (evaluating '$.fn') file: http://localhost:3000/bootstrap3-typeahead.js line: 459

Do I set it up wrong or it is a bug?

Thanks.

**Comment by mradamlacey** [comment]
You should just need to build the project first with

```
grunt
```

From the command line.

**Comment by shihch** [comment]
Yeah, I did use npm install and grunt build:dev as you documented in the Readme.
But when I run 'grunt' just get the error:

```
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.
```
