### ISSUE TITLE
Multiple Indexes

### ISSUE THREAD

**Issue by dillera** [mradamlacey/elasticsearch-tableau-connector#72]
Hello- this is awesome but I'm having some issues using it and connecting to multiple Indexes on my ES cluster. I can create 2 but then clicking on one just overwrites the other one.

I've tried even running 2 instances (changing the port) and it still only keeps one as the data source-- overwrite the other as I click and load it.

Is there something I'm missing to use this plugin to pull in 2 distinct indexes from the same ES cluster?

**Comment by maximeloizeau** [comment]
If I am understanding your issue correctly, you need to create 2 connections to have 2 indexes. You can create the two connections from the same workbook if you need to join them.

If you edit your datasource, it will overwrite your previous index.

**Comment by dillera** [comment]
Thanks for replying back. Yes, I'm trying to connect to two indexes in ES. I need Tableau to read both and do some joins.

However, if I setup 2 datasources they overwrite each other as they are loaded into Tableau.

I even copied over the repo to a new dir (i'm running this on my OSX Sierra computer) and ran a new instance of node on a new port- however the same thing seems to have happened, after setting up 2 datasources using the same hostname (my mac) but the different ports 3000 and 3001.

I'm wondering how to connect to 2 (or more) indexes on the same ES instance using your wonderful tool.

**Comment by mradamlacey** [comment]
You should just need to give each connection a unique name and Tableau shouldn't overwrite them.

**Comment by dillera** [comment]
I know, but that is not what is happening. Each selection of the 2nd instance over-writes the first one.

**Comment by dillera** [comment]
We actually just started sending our data into Mysql and that works normally with Tableau.

**Comment by michaelsimons1987** [comment]
Hi Andy. How are you doing this? What tools are you using? Thanks
michael@msimons.uk <mailto:michael@msimons.uk> to communicate over email if easier for you!

Thanks.

**Comment by dillera** [comment]
Well, it's only because we are using AWS. We have a stream of incoming messages from a source that arrive via the AWS API-GW and we then use SNS/SQS to duplicate the stream to trigger lambdas which in turn load the data both into ES and also Aurora (mysql). We had to do this because we couldn't get the plugin (which is great) working the way we wanted. Once in Mysql we can also use some more advanced joins which were difficult in ES/Kib.

We use the ELK for daily monitoring dashboards and the mysql for Tableau.
