### ISSUE TITLE
Unable to get elasticsearch types

### ISSUE THREAD

**Issue by phytopius** [mradamlacey/elasticsearch-tableau-connector#73]
The index name field shows me all correct indexes but the type fails.
[Imgur Link](http://imgur.com/a/fdI5a)

When I enter the type "log" manually and try to get a preview this error shows up
Unable to get Elasticsearch types, status code: 400; No handler found for uri [//productivity/log/_mapping] and method [GET] Bad Request

When I run "get /productivity/log/_mapping" in kibana it show me the mapping of the data correctly.

I added following commands to elasticsearch.yml:
http.cors.enabled: true
http.cors.allow-origin: "*"

**Comment by mradamlacey** [comment]
From your screenshot, you have selected an index named 'modified'.  The error message you have in the comment references an index named 'productivity'... which index do you have an issue with?

The error message in your screenshot indicates an index named 'modified' does not exist.

**Comment by mradamlacey** [comment]
Also - I just noticed there's a bug when leaving a trailing backslash in the Elasticsearch URL field.

You can workaround this for now by removing that backslash and let me know the results.
