### ISSUE TITLE
Loading time

### ISSUE THREAD

**Issue by RuilingLiu** [mradamlacey/elasticsearch-tableau-connector#9]
Hi,

Thank you for the connector!

I tried to load 1 record from my Elasticsearch endpoint, so I set the "Batch size of per request to Elasticsearch" and "Total limit on number of rows to sync" to 1.

It took me more than 25 minutes, but nothing was loaded. The size of each record is very small.

How long does it usually take to load the metadata?

**Comment by mradamlacey** [comment]
I'm wasn't able to reproduce that.

Could you share the output of the Tableau SDK log? Or browser console log?

It should be under a few seconds to pull back a dataset of that size.  Are you using the connector from Tableau server?  Or just using Tableau desktop to reference a locally running instance of the connector web server?

**Comment by RuilingLiu** [comment]
I am using Tableau desktop to connect to a local Elasticsearch endpoint. And there was nothing in the browser console log.

**Comment by mradamlacey** [comment]
Ok, I would suggest using the Tableau Web Connector SDK to connect to test this and provide me the console output of the SDK UI and the brower javascript console.

I think it will be easy to troubleshoot from there.

**Comment by RuilingLiu** [comment]
Hi,

I tried to use the Tableau Web Connector SDK to connect. But I cannot load the Elasticsearch Tableau WDC from the Tableau WDC simulator. It says "Please open this URL from within Tableau".

I am new to Tableau. Thank you for your help!

<img width="1340" alt="screen shot 2016-04-25 at 10 27 41 am" src="https://cloud.githubusercontent.com/assets/11318005/14789064/7a3ce2c6-0ad0-11e6-91db-31161aa0e4fc.png">

**Comment by mradamlacey** [comment]
Currently the connector only works with the 1.1.0 WDC API.

To test with it, you should use the [old simulator](http://tableau.github.io/webdataconnector/Simulator/old_simulator.html).

I'll open a separate issue to update the connector to work with the latest WDC API (1.1.1)
